---
title: "SCWG workshop feedback"
output: html_document
---

```{r PACKAGES, echo=FALSE, message=FALSE, warning=FALSE}
#Load necessary packages
library(ggplot2)    
library(knitr)       
library(grid)       
library(reshape2)
```

```{r HELLO}
# still working on cleaning this up - hopefully good enough for mtg to get a sense.

# still to do:
#         1. add total counts to top of the two 'across workshop' plots
#         2. figure out how to label first 8 items with "strongly disagree..." without changing axis dimensions
#         3. summarize who was in attendance (job title, number of years computing experience, etc)
#         4. figure out how to make workshop comments look nicer
#         5. anything else?
```

```{r SETUP, echo=FALSE, message=FALSE, warning=FALSE}
opts_chunk$set(fig.width=12)

# Read in data
feedback <- read.csv('SCWG_Workshop_Evaluation_2016-06-04.csv', header=TRUE, sep=",") 
```

```{r CLEANING, echo=FALSE, message=FALSE, warning=FALSE}

##### Set up and clean dataframe

# Make a dataframe
feedback <- data.frame(feedback)  

# Assign workshop labels
feedback$workshop_may_17[feedback$workshop_may_17 == 1] <- "Ask us anything about computers" 
feedback$workshop_may_17[feedback$workshop_may_17 == 2] <- "Introduction to programming"  
feedback$workshop_may_17[feedback$workshop_may_17 == 3] <- "Introduction to Linux and the shell"
feedback$workshop_may_17[feedback$workshop_may_17 == 4] <- "Introduction to R (i)"  
feedback$workshop_may_18[feedback$workshop_may_18 == 1] <- "Managing code, experiments, and data"  
feedback$workshop_may_18[feedback$workshop_may_18 == 2] <- "Automating in Linux"
feedback$workshop_may_18[feedback$workshop_may_18 == 3] <- "Organizing your files with GitHub"
feedback$workshop_may_19[feedback$workshop_may_19 == 1] <- "Spreadsheets"
feedback$workshop_may_19[feedback$workshop_may_19 == 2] <- "SPSS"
feedback$workshop_may_19[feedback$workshop_may_19 == 3] <- "Web design for research"
feedback$workshop_may_19[feedback$workshop_may_19 == 4] <- "MS Access"
feedback$workshop_may_24[feedback$workshop_may_24 == 1] <- "Introduction to R (ii)"
feedback$workshop_may_24[feedback$workshop_may_24 == 2] <- "Advanced R"
feedback$workshop_may_24[feedback$workshop_may_24 == 3] <- "Introduction to REDCap"
feedback$workshop_may_25[feedback$workshop_may_25 == 1] <- "Introduction to Python"
feedback$workshop_may_25[feedback$workshop_may_25 == 2] <- "Introduction to the SCC"
feedback$workshop_may_25[feedback$workshop_may_25 == 3] <- "Advanced SCC: Scientific computing"
feedback$workshop_may_25[feedback$workshop_may_25 == 4] <- "MATLAB"
feedback$workshop_may_26[feedback$workshop_may_26 == 1] <- "Writing papers with RStudio"
feedback$workshop_may_26[feedback$workshop_may_26 == 2] <- "How to (ethically) use Photoshop for figures"
feedback$workshop_may_26[feedback$workshop_may_26 == 3] <- "Python for MRI"
feedback$workshop_may_26[feedback$workshop_may_26 == 4] <- "Advanced REDCap"
feedback$workshop_may_27[feedback$workshop_may_27 == 1] <- "SPSS"

# Remove test record
feedback <- feedback[feedback$comments != "test delete", ]  

# Remove incomplete records 
feedback <- feedback[feedback$scwg_workshop_evaluation_questionnaire_timestamp != "[not completed]", ]

# Remove record 73 as workshop is not indicated
feedback <- feedback[feedback$record_id != 73,] 

# Tidy up workshop names (collapse workshop names across days)
feedback <- cbind(feedback[1:4], "workshop_name" = as.character(na.omit(c(t(feedback[5:11])))), feedback[12:ncol(feedback)]) 

# Remove unnecessary columns 
feedback <- subset(feedback, select = -c(1:4, 32))  

# Sort dataframe alphabetically by workshop name
feedback <- feedback[order(feedback$workshop_name) , ]

# Add 'Research Coordinator' to 'job_title' variable for 5 participants
feedback[c(18,19, 33, 39, 67), 16]= 8

# Add 'Undergraduate Student' to 'job_title' variable for 7 participants
feedback[c(6, 26, 30, 34, 47, 71, 78), 16] = 10

# Assign labels to 'job_title'
feedback$job_title[feedback$job_title == 1] <- "Research Assistant"
feedback$job_title[feedback$job_title == 2] <- "Research Analyst"
feedback$job_title[feedback$job_title == 3] <- "Research Methods Specialist"
feedback$job_title[feedback$job_title == 4] <- "Graduate Student"
feedback$job_title[feedback$job_title == 5] <- "Post-doctoral Fellow"
feedback$job_title[feedback$job_title == 6] <- "Scientist"
feedback$job_title[feedback$job_title == 7] <- "Other"
feedback$job_title[feedback$job_title == 8] <- "Research Coordinator"
feedback$job_title[feedback$job_title == 9] <- "Manager"
feedback$job_title[feedback$job_title == 10] <- "Undergraduate Student"

# Change labelled 'job_title' into factor
feedback$job_title <- as.factor(feedback$job_title)

# Assign labels to 'job_description'
feedback$job_description[feedback$job_description == 1] <- "Administrative"
feedback$job_description[feedback$job_description == 2] <- "Clinical"
feedback$job_description[feedback$job_description == 3] <- "Computing"
feedback$job_description[feedback$job_description == 4] <- "Genetics"
feedback$job_description[feedback$job_description == 5] <- "Imaging"
feedback$job_description[feedback$job_description == 6] <- "IT"
feedback$job_description[feedback$job_description == 7] <- "Statistics"
feedback$job_description[feedback$job_description == 8] <- "Other"

# Change labelled 'job_description' into factor
feedback$job_description <- as.factor(feedback$job_description)

# Change 'job_comp_exper' into factor and assign levels and labels
feedback$job_comp_exper<- factor(feedback$job_comp_exper, 
levels = c(5:0), labels = c("5 or more years", "4 years", "3 years", "2 years", "1 year", "None"))

```

```{r PLOTTING_DATAFRAME, echo=FALSE, message=FALSE, warning=FALSE}

# Make a datafrom for plotting - reverse alphabetical
fb.plot <- feedback[order(feedback$workshop_name, decreasing = TRUE) , ]
fb.plot$workshop_name <- factor(fb.plot$workshop_name, levels = unique(fb.plot$workshop_name))
```

```{r COMBINED_FEEDBACK_5PT, echo=FALSE, message=FALSE, warning=FALSE}

#### Plot 5pt Likert feedback items over loop of all workshops - combined

# make vector of plot titles
Plot_titles_1 <- c(
  'Overall, I am glad I attended the workshop',
  'I was able to follow along with and understand the material',
  'The workshop format was a good way for me to learn about this content',
  'The skills I learned will help me do my job better',
  'I will recommend this workshop to my colleagues',
  'The instructor was knowledgeable about the topic',
  'The instructor and/or helpers were able to answer any questions I had')

# make data into longform
fb.plot2 <- fb.plot[2:8]
row.names(fb.plot2) <- NULL
fb.plot2 <- melt(data = fb.plot2, measure.vars = names(fb.plot2[1:7]), variable.name = "Question", value.name = "Rating")

# set up plot
plot <- ggplot(fb.plot2, aes(x=Question, y=Rating))

# plot the mean
plot <- plot + stat_summary(fun.y=mean, geom="point", size=3.5, color = "red")

# set up jitter effect
plot <- plot + geom_jitter(shape=16, position=position_jitter(height = 0.1, width = 0.4))

# set axis range
plot <- plot + coord_cartesian(ylim = c(.75, 5.25))

# change axis labels
plot <- plot + scale_x_discrete(labels = Plot_titles_1) 

# make it prettier
plot <- plot + theme_bw() + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), axis.title.y = element_blank(), axis.title.x = element_blank()) + ggtitle("Combined feedback across all workshops") +
   scale_y_continuous(breaks = c(1,2,3,4,5), labels = c('strongly disagree', 'disagree', 'neither agree nor disagree', 'agree', 'strongly agree'))

# flip to horizontal orientation
plot <- plot + coord_flip() 

# labels dot counts
plot <- plot + annotate("text", y = 1:5, x= 7.75, label = c("test", "2", "3", "4", "5"), color = "red") + annotate("rect", xmin = 7, xmax = 8, ymin = 5, ymax = 5, alpha = .2)

print(plot)
```
  
<br>
<br>
<br>
<br>
<br>

```{r PLOTTING_IND_5PT, echo=FALSE, message=FALSE, warning=FALSE}

#### Plot 5pt Likert feedback items over loop of all individual workshops

# make vector of plot titles
Plot_titles_1 <- c(
  'Overall, I am glad I attended the workshop',
  'I was able to follow along with and understand the material',
  'The workshop format was a good way for me to learn about this content',
  'The skills I learned will help me do my job better',
  'I will recommend this workshop to my colleagues',
  'The instructor was knowledgeable about the topic',
  'The instructor and/or helpers were able to answer any questions I had')

# initiate list
Plots_list_1 <- list()

# initiate title counter
ctr <- 1

# create for loop to make plots
for (i in names(feedback[2:8]))  {

# set up plot
plot <- ggplot(fb.plot, aes_string('workshop_name', i)) 

# set up jitter effect 
plot <- plot + geom_point(stat = 'identity', position = position_jitter(height = 0.1, width = 0.2), colour = 'dark grey')  

# plot the mean
plot <- plot + stat_summary(fun.y = "mean", colour = 'red', size = 3.5, geom = 'point') +
  
# write title
  ggtitle(Plot_titles_1[ctr]) + 
  
# make it prettier
  theme_bw() + 
  scale_x_discrete(name='') + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), axis.title.x = element_blank()) + scale_y_continuous(breaks = c(1,2,3,4,5), labels = c('strongly disagree', 'disagree', 'neither agree nor disagree', 'agree', 'strongly agree'), limits = c(.75,5.25))

# flip to horizontal orientation
plot <- plot + coord_flip() 

# store in list
Plots_list_1[[i]] <- plot 

ctr <- ctr + 1
}

print(Plots_list_1[[1]])
print(Plots_list_1[[2]])
print(Plots_list_1[[3]])
print(Plots_list_1[[4]])
print(Plots_list_1[[5]])
print(Plots_list_1[[6]])
print(Plots_list_1[[7]])
```

```{r COMBINED_FEEDBACK_3PT, echo=FALSE, message=FALSE, warning=FALSE}

#### Plot 3pt Likert feedback items over loop of all workshops - combined

# make vector of plot titles
Plot_titles_2 <- c(
  'Amount of content',
  'Difficulty of content',
  'Pace of instruction',
  'Amount of time for workshop',
  'Amount of time on exercises / examples')

# make data into longform
fb.plot3 <- fb.plot[9:13]
row.names(fb.plot3) <- NULL
fb.plot3 <- melt(data = fb.plot3, measure.vars = names(fb.plot3[1:5]), variable.name = "Question", value.name = "Rating")

# set up plot
plot <- ggplot(fb.plot3, aes(x=Question, y=Rating))

# plot the mean
plot <- plot + stat_summary(fun.y=mean, geom="point", size=3.5, color = "red")

# set up jitter effect
plot <- plot + geom_jitter(shape=16, position=position_jitter(height = 0.1, width = 0.4))

# set axis range
plot <- plot + coord_cartesian(ylim = c(.75, 5.25))

# change axis labels
plot <- plot + scale_x_discrete(labels = Plot_titles_2) 

# make it prettier
plot <- plot + theme_bw() + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), axis.title.y = element_blank(), axis.title.x = element_blank()) + ggtitle("Combined feedback across all workshops") + scale_y_continuous(breaks = c(-1,0,1), labels = c('not enough', 'just right', 'too much'))

# flip to horizontal orientation
plot <- plot + coord_flip() 

print(plot)
```

```{r PLOTTING_IND_3PT, echo=FALSE, message=FALSE, warning=FALSE}

#### Plot 3pt Likert feedback items over loop of all individual workshops

# make vector of plot titles
Plot_titles_2 <- c(
  'Amount of content',
  'Difficulty of content',
  'Pace of instruction',
  'Amount of time for workshop',
  'Amount of time on exercises / examples')

# initiate list
Plots_list_2 <- list()

# initiate title counter
ctr <- 1

# create for loop to make plots
for (i in names(feedback[9:13]))  {

# set up plot
plot <- ggplot(fb.plot, aes_string('workshop_name', i)) 

# set up jitter effect 
plot <- plot + geom_point(stat = 'identity', position = position_jitter(height = 0.1, width = 0.2), colour = 'dark grey')  

# plot the mean
plot <- plot + stat_summary(fun.y = "mean", colour = 'red', size = 3.5, geom = 'point')

# set axis range
plot <- plot + scale_y_continuous(limits = c(-1.25, 1.25)) +
  
# write title
  ggtitle(Plot_titles_2[ctr]) + 
  
# make it prettier
  theme_bw() + 
  scale_x_discrete(name='') + 
  theme(plot.title = element_text(size=11), 
        axis.ticks = element_blank(), 
        axis.title.x = element_blank()) + 
   scale_y_continuous(breaks = c(-1,0,1), labels = c('not enough', 'just right', 'too much'))

# flip to horizontal orientation
plot <- plot + coord_flip() 

# store in list
Plots_list_2[[i]] <- plot 

ctr <- ctr + 1
}

print(Plots_list_2[[1]])
print(Plots_list_2[[2]])
print(Plots_list_2[[3]])
print(Plots_list_2[[4]])
print(Plots_list_2[[5]])
```

```{r COMMENTS, results="asis", message=FALSE, warning=FALSE}

# working on cleaning up the comments - will delete blank cells, change formatting, and make dimensions to table consistent, and try to figure out what's going wrong in some places...
# including in case anyone has comments on how this information can be better displayed

for (i in levels(feedback$workshop_name)) {
  workshop_feedback = subset(feedback, workshop_name == i)
  comments = workshop_feedback[,c("best", "improve", "comments")]
  comments = data.frame(apply(comments, 2, FUN=function(x) gsub('\\s+', ' ', x)))
  cat(paste("\n##", i,'\n'))
  print(kable(comments, caption=i, row.names=F, format="markdown"))
  
}
```

```{r JOB_TITLE,  echo=FALSE, message=FALSE, warning=FALSE}

# Reorder levels of 'job_title' to display in increasing frequency on plot
feedback$job_title <- factor(feedback$job_title, levels = names(sort(table(feedback$job_title), decreasing = TRUE)))

# make a histogram of 'job_title'
plot <- ggplot(feedback[!is.na(feedback$job_title),], aes(job_title)) + geom_bar(fill = 'light grey') +
  geom_text(aes(label = paste0(format(100* ..count../sum(..count..), digits = 2), '%'), hjust = 1.25, colour = 'red', y = ..count..), stat = 'count') +
  theme_bw() +
  ggtitle('Job title') + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), legend.position = 'none') +
  coord_flip() +
  scale_y_continuous(name = '') +
  scale_x_discrete(name = '')
plot
```

```{r RESEARCH_FOCUS,  echo=FALSE, message=FALSE, warning=FALSE}

# Reorder levels of 'job_description' to display in increasing frequency on plot
feedback$job_description <- factor(feedback$job_description, levels = names(sort(table(feedback$job_description), decreasing = TRUE)))

# make a histogram of 'job_description'
plot <- ggplot(feedback[!is.na(feedback$job_description),], aes(job_description)) + geom_bar(fill = 'light grey') +
  geom_text(aes(label = paste0(format(100* ..count../sum(..count..), digits = 2), '%'), hjust = 1.25, colour = 'red', y = ..count..), stat = 'count') +
  theme_bw() +
  ggtitle('Research focus') + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), legend.position = 'none') +
  coord_flip() +
  scale_y_continuous(name = '') +
  scale_x_discrete(name = '')
plot
```

```{r COMPUTING_EXPERIENCE,  echo=FALSE, message=FALSE, warning=FALSE}

# make a histogram of 'job_comp_exper'
plot <- ggplot(feedback[!is.na(feedback$job_comp_exper),], aes(job_comp_exper)) + geom_bar(fill = 'light grey') +
  geom_text(aes(label = paste0(format(100* ..count../sum(..count..), digits = 2), '%'), hjust = 1.25, colour = 'red', y = ..count..), stat = 'count') +
  theme_bw() +
  ggtitle('Scientific computing experience') + 
  theme(plot.title = element_text(size=11), axis.ticks = element_blank(), legend.position = 'none') +
  coord_flip() +
  scale_y_continuous(name = '') +
  scale_x_discrete(name = '')

plot
```